services:
  postgres:
    build: ./docker/postgres/
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_django_saas:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  
  web:
    build: .
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
  
volumes:
  postgres_data_django_saas:

